name: Build Little Kernel

on:
  push:
    branches: [ lk-root-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: lk-root-branch

      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build LK
        run: |
          make PROJECT=k65v1_64_bsp TOOLCHAIN_PREFIX=arm-none-eabi-

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lk-binaries
          path: build-k65v1_64_bsp/lk.bin
